server:
  port: 8090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: oracle
    ##url: jdbc:oracle:thin:@1sdfasf8:1521:orcl
    url: jdbc:oracle:thin:@192.168.0.39:1521:orcl
    username: schoolsafe

sql:
  #执行的sql
  sqlStr1: SELECT  * FROM  T_USER_LOGIN_INFO where LOGIN_TIME>=? and LOGIN_TIME<=?
  sqlStr2: